server:
  port: 5001
security:
  oauth2:
    resource:
      id: course-auth
      user-info-uri: http://localhost:8080/passport/principal
      prefer-token-info: false
spring:
  datasource:
    url: jdbc:mysql:///cloud_course?useSSL=false
    username: root
    password: 19970914
  devtools:
    restart:
      trigger-file: trigger.txt
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
feign:
  hystrix:
    enabled: true

