eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/
spring:
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
zuul:
  routes:
    auth:
      path: /passport/**
      sensitiveHeaders:
      serviceId: course-auth
    student:
      path: /student/**
      serviceId: course-student
      sensitiveHeaders:
    teacher:
      path: /teacher/**
      serviceId: course-teacher
    admin:
      path: /admin/**
      serviceId: course-admin
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8080/passport/principal
      prefer-token-info: false
