server:
  port: 3001
security:
  oauth2:
    resource:
      id: course-auth
      user-info-uri: http://localhost:8080/passport/principal
      prefer-token-info: false
spring:
  datasource:
    url: jdbc:mysql:///cloud_course?useSSL=false
    username: root
    password: 19970914
  devtools:
    restart:
      trigger-file: trigger.txt
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
course:
  pageSize: 5
management:
  security:
    enabled: false
