server:
  port: 2001
spring:
  datasource:
    url: jdbc:mysql:///cloud_course?useSSL=false
    username: root
    password: 19970914
security:
  oauth2:
    resource:
      filter-order: 3
    client:
      client-id: webapp
      client-secret: webapp
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: classpath:cn.yozora.courseauth.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

