server:
  port: 5001
spring:
  datasource:
    url: jdbc:mysql:///cloud_course?useSSL=false
    username: root
    password: 19970914
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  devtools:
    restart:
      trigger-file: trigger.txt
  sleuth:
    sampler:
      percentage: 1.0
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
feign:
  hystrix:
    enabled: true
security:
  oauth2:
    resource:
      id: course-auth
      user-info-uri: http://localhost:8080/passport/principal
      prefer-token-info: false

